cloudAdministratorUsername: "admin"
cloudIntegrationPlatformEndpoint: "*"
cloudIntegrationPlatformNamespace: "integration"
productionDeployment: PRODUCTION_DEPLOY
clusterDomainSuffix: cluster.local

global:
  registry: "cp.icr.io/cp/icp4i/apic"
  registrySecret: "PULL_SECRET"
  createCrds: true
  storageClass: "BLOCK_STORAGE"
  mode: "DEPLOY_MODE"
  routingType: "ROUTE_TYPE"
  certSecret: ""
  extraValuesConfig: ""

# apiconnect-operator
operator:
  arch: amd64
  registry: ""
  image: "apiconnect-operator"
  tag: 2019-11-19-17-26-15-5ba74bf0514e87ef44b35744b66d6c4179f720e1
  pullPolicy: IfNotPresent
  helmTlsSecret: "HELM_TLS_SECRET"
  serviceAccount:
    create: true
    name:
  tiller:
    useNodePort: false
    nodePort: 31514

# management subsystem
management:
  enabled: true
  certSecret: ""
  storageClass: ""
  platformApiEndpoint: "mgmt.PROXY_ENDPOINT"
  consumerApiEndpoint: "mgmt.PROXY_ENDPOINT"
  cloudAdminUiEndpoint: "mgmt.PROXY_ENDPOINT"
  apiManagerUiEndpoint: "mgmt.PROXY_ENDPOINT"
cassandra:
  cassandraClusterSize: REPLICA_COUNT
  cassandraMaxMemoryGb: 9
  cassandraVolumeSizeGb: 50
cassandraBackup:
  cassandraBackupAuthUser: ""
  cassandraBackupAuthPass: ""
  cassandraBackupHost: ""
  cassandraBackupPath: /backups
  cassandraBackupPort: 22
  cassandraBackupProtocol: sftp
  cassandraBackupSchedule: 0 0 * * *
cassandraPostmortems:
  cassandraPostmortemsAuthUser: ""
  cassandraPostmortemsAuthPass: ""
  cassandraPostmortemsHost: ""
  cassandraPostmortemsPath: /cassandra-postmortems
  cassandraPostmortemsPort: 22
  cassandraPostmortemsSchedule: 0 0 * * *

# portal subsystem
portal:
  enabled: true
  certSecret: ""
  storageClass: ""
  portalDirectorEndpoint: "padmin.PROXY_ENDPOINT"
  portalWebEndpoint: "portal.PROXY_ENDPOINT"
  adminStorageSizeGb: 1
  backupStorageSizeGb: 5
  dbLogsStorageSizeGb: 2
  dbStorageSizeGb: 12
  wwwStorageSizeGb: 5

portalBackup:
  siteBackupAuthUser: ""
  siteBackupAuthPass: ""
  siteBackupHost: ""
  siteBackupPath: /backups
  siteBackupPort: 22
  siteBackupProtocol: sftp
  siteBackupSchedule: 0 2 * * *

# analytics subsystem
analytics:
  enabled: true
  certSecret: ""
  storageClass: ""
  esStorageClass: ""
  enableMessageQueue: false
  mqStorageClass: ""
  analyticsIngestionEndpoint: "ai.PROXY_ENDPOINT"
  analyticsClientEndpoint: "ac.PROXY_ENDPOINT"
  coordinatingMaxMemoryGb: 12
  dataMaxMemoryGb: 12
  dataStorageSizeGb: 200
  masterMaxMemoryGb: 12
  masterStorageSizeGb: 5

# gateway subsystem
gateway:
  enabled: true
  certSecret: ""
  storageClass: ""
  apiGatewayEndpoint: "apigw.PROXY_ENDPOINT"
  gatewayServiceEndpoint: "apigwd.PROXY_ENDPOINT"
  replicaCount: REPLICA_COUNT
  maxCpu: 4
  maxMemoryGb: 6
  v5CompatibilityMode: true
  enableTms: false
  tmsPeeringStorageSizeGb: 10
  highPerformancePeering: HIGH_PERFORMANCE_PEERING
  image: "datapower-api-gateway"
  imageTag: 2018.4.1.8-314665-release-prod
  monitoringImage: "k8s-datapower-monitor"
  monitoringImageTag: 2018.4.1-25-d256b8f
  odTracing:
    enabled: false
    odManagerNamespace: "tracing"
    odAgentImage: "icp4i-od-agent"
    odAgentImageTag: "1.0.0"
    odCollectorImage: "icp4i-od-collector"
    odCollectorImageTag: "1.0.0"
  imagePullPolicy: IfNotPresent
