apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibmcloud-cluster-ca-cert-fix
  namespace: kube-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibmcloud-cluster-ca-cert-fix
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
