---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mq1
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/mq1
    server: 172.18.4.119
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mq2
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/mq2
    server: 172.18.4.119
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mq3
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/mq3
    server: 172.18.4.119
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
