apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: data-mq-dev-ibm-mq-0
  namespace: mq
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
